import { environment } from "src/environments/environment.development";

export const appConfig = {
  mobile: "",
  withoutLoginUrls: ["/"],
  baseApiUrl: environment.apiURL,
  payment_gateway_merchant_code: "MX20151",
  payment_gateway_payitem_id: "Default_Payable_MX20151",
  perPageDefault: 1,
  perPageArray: [12, 24, 36, 48, 60],
  perPageTblArray: [10, 20, 30, 40, 50, 100],
  perPageTblDefault: 1,
  date_format: "DD-MM-YYYY",
  yearRange: 100,
  GOOGLE_AUTH_KEY: "",
  loader_timer: 20000,
  statusCode: {
    ok: 200,
    created: 201,
    accepted: 202,
    noContent: 204,
    found: 302,
    temporaryRedirect: 307,
    badRequest: 400,
    unauthorized: 401,
    paymentRequired: 402,
    forbidden: 403,
    notFound: 404,
    notAcceptable: 406,
    conflict: 409,
    preconditionFailed: 412,
    payloadTooLarge: 413,
    unsupportedMediaType: 415,
    invalidToken: 498,
    internalServerError: 500,
    notImplemented: 501,
    badGateway: 502,
    serviceUnavailable: 503,
    gatewayTimeout: 504,
    httpVersionNotSupported: 505,
    networkAuthenticationRequired: 511,
  },
  pattern: {
    USERNAME: /[a-zA-Z0-9_]{3,15}$/gi,
    NAME: /^[a-zA-Z]+([ '-][a-zA-Z]+)*$/,
    CITY: /^[a-zA-Z]+([ '-][a-zA-Z]+)*$/,
    EMAIL:/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    POSTAL_CODE:
      /(^\d{5}(-\d{4})?$)|(^[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1} *\d{1}[A-Z]{1}\d{1}$)/, // /(^\d{5}$)|(^\d{5}-\d{4}$)/,
    SUB_DOMAIN: /^[/a-z/A-Z][a-zA-Z0-9-]*[^/-/./0-9]$/,
    SIMPLE_PHONE_NO: /^[1-9]\d{9}$/,
    FORMATTED_PHONE_NO: /\(?\d{3}\)?-? *\d{3}-? *-?\d{4}/,
    TASK_CODE: /^[0-9999]{1,4}$/,
    SSN: /^((\d{3}-?\d{2}-?\d{4})|(X{3}-?X{2}-?X{4}))$/,
    TRANSACTION_PIN: /d{4}$/,
    PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]+$/,
  },
  email: {
    abuse_email: "no-reply@radarhostapp.com",
    copyright: new Date().getFullYear() + " Copyright Afronet",
    logo_url: "/public/images/logo.png",
  },
  roles: {
    SUPER_ADMIN: 1, //Super Administrator
    ADMIN: 2, //Administrator
    MEMBER: 3,
    AGENT: 4,
  },
  role_type: {
    SUPER_ADMIN: { id: "1", meta: "super_admin", name: "Super Admin" },
    ADMIN: { id: "2", meta: "admin", name: "Admin" },
    MEMBER: { id: "3", meta: "member", name: "Member" },
    AGENT: { id: "4", meta: "agent", name: "Agent" },
  },
  upload_dir: {
    USER_PROFILE_PIC: `${environment.apiURL}/ProfileImages/`,
    PICTURES: `${environment.apiURL}/public/images/`,
    META_IMAGE: `${environment.apiURL}/metaImage/`,
    BLOG_PIC: "/public/uploads/blogs/",
    BLOG_CATEGORY_PIC: "/public/uploads/blogs/category/",
    DEFAULT_MALE_PIC: "assets/images/male_avatar.jpg",
    DEFAULT_FEMALE_PIC: "assets/images/female_avatar.jpg",
    DEFAULT_MALE_WHITE_PIC: "/public/images/male_avatar_white.png",
    DEFAULT_FEMALE_WHITE_PIC: "/public/images/female_avatar_white.png",
    COMPANY_LOGO_DIR: "/public/uploads/logos/",
    DEFAULT_COMPANY_LOGO: "/public/images/default_logo.png",
    DOCUMENTS_DIR: "/uploads/",
  },
  IS_PROFILE_PICTURE: {
    yes: 1,
    no: 0,
  },
  WITHDRAWAL_STATUS: [
    { value: 0, label: "Pending" },
    { value: 1, label: "In Progress" },
    { value: 2, label: "Completed" },
    { value: 3, label: "Declined" },
  ],
  files: {
    MAX_IMG_SIZE: 20 * 2000 * 2000,
  },
  storage: {
    IS_MATCHED: "_an_mt",
    MATCH_ID: "_an_mt_id",
    IS_PHONE_VERIFIED: "_an_ph",
    IS_EMAIL_VERIFIED: "_an_em",
    IS_SUBSCRIBED: "_an_sub",
    IS_ACCOUNT_PAUSED: "_an_p",
    IS_NEW: "_an_new",
    STRIPE_DATA: "_ansd",
    ACTIVE_EVENT_LINK: "_anael",
    USER_LATITUDE: "_anulat_",
    USER_LONGITUDE: "_anulong_",
    USER_CURRENT_LOCATION: "_anucurloc",
    USER_CURRENT_CURRENCYCODE: "_anucurc",
    USER_CURRENT_CURRENCYSYMBOL: "_anucursb",
    LONG_TIMEZONE: "_anltz",
    SHORT_TIMEZONE: "_anstz",
    USER_CURRENT_CITY: "_anucc_",
    USER_CURRENT_LONG_STATE: "_anucls_",
    USER_CURRENT_SHORT_STATE: "_anucss_",
    USER_CURRENT_COUNTRY: "_anucco_",
    USER_CURRENT_COUNTRYCODE: "_anuccocd_",
    USER_CURRENT_POSTALCODE: "_anucpc_",
    USER_CURRENT_NEIGHBORHOOD: "_anucnb_",
    USER_CURRENT_AXIS: "_anuca_",
    USER_CURRENT_ZONE: "_anucz_",
    USER_DATA: "_an_user_data",
    USER_SOCIAL_HANDLES_DATA: "_an_user_social_handles",
    USER: "_an_u_",
    USERNAME: "_an_uname_",
    USER_EMAIL: "_an_uemail_",
    PROFILE_PIC: "_an_u_profile_pic",
    HAS_PROFILE_PIC: "_an_u_has_profile_pic",
    PERMISSIONS: "_an_u_permissions",
    TOKEN: "_an_t_",
    OTP_TOKEN: "_an_ot_",
    TOKEN_EXPIRY: "_an_te_",
    LOCKED: "_an_lck_",
    ROLE: "_an_r_",
    USER_ID: "_an_ui_",
    MOBILE: "_an_umobile_",
    USERFNAME: "_an_fn_",
    USERMNAME: "_an_mn_",
    USERLNAME: "_an_ln_",
    REMEMBER_ME: "_an_remember_me",
  },
  STATUS: {
    ACTIVE: 1,
    INACTIVE: 0,
  },
  loadTimer: 7000,
  INACTIVITY_TIMER: {
    "10MINS": 10 * 60 * 1000,
    "1MIN": 1 * 60 * 1000,
    "5MINS": 5 * 60 * 1000,
    "30SECS": 30 * 1000,
  }
};
